# Generated by Django 5.0.3 on 2024-04-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('path', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('downloads_count', models.IntegerField(default=0)),
                ('emailed_count', models.IntegerField(default=0)),
            ],
        ),
    ]
