# Generated by Django 5.0.3 on 2024-04-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0002_remove_file_path_file_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-downloads_count']},
        ),
    ]
