# Generated by Django 5.0.3 on 2024-04-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0003_alter_file_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-date']},
        ),
    ]
