# Generated by Django 5.0.3 on 2024-04-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0005_user_is_email_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
