# Generated by Django 5.0.3 on 2024-04-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0006_alter_user_options_rename_is_staff_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
